# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/imdev'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-xml
      - libfftw3-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libudunits2-dev
      - liblwgeom-dev

# Prevents Travis timeout for building
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
